<a href="https://colab.research.google.com/github/AishwariyaRaj/DataScience/blob/main/Task1_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TASK1-**4  (**6** QUESTION)

**TASK - 2,QUESTION - 1**

**IMPORTING LIBRARY FUNCTION**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

1.i) Write a NumPy program to convert a list and tuple into arrays

In [ ]:
my_list = [1, 2, 3, 4, 5]
array_from_list = np.array(my_list)

# Convert a tuple to a NumPy array
my_tuple = (6, 7, 8, 9, 10)
array_from_tuple = np.array(my_tuple)

print("Array from list:", array_from_list)
print("Array from tuple:", array_from_tuple)

Array from list: [1 2 3 4 5]
Array from tuple: [ 6  7  8  9 10]


ii)Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit
degrees and vice versa. Values have to be stored into a NumPy array

In [ ]:
def celsius_to_fahrenheit(celsius_array):
    return (celsius_array * 9/5) + 32
def fahrenheit_to_celsius(fahrenheit_array):
    return (fahrenheit_array - 32) * 5/9
celsius_values = np.array([0, 25, 37.5, 100])
fahrenheit_values = celsius_to_fahrenheit(celsius_values)
celsius_values_back = fahrenheit_to_celsius(fahrenheit_values)

print("Centigrade to Fahrenheit:", fahrenheit_values)
print("Fahrenheit to Centigrade:", celsius_values_back)

Centigrade to Fahrenheit: [ 32.   77.   99.5 212. ]
Fahrenheit to Centigrade: [  0.   25.   37.5 100. ]


**TASK - 3, QUESTION - 16**

2)Write a Pandas program to check for inequality of two given DataFrames.

In [ ]:
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': ['X', 'Y', 'Z']})
df2 = pd.DataFrame({'A': [1, 2, 4], 'B': ['X', 'Y', 'W']})

# Check for inequality
inequality_check = df1.ne(df2)

print("Original DataFrame 1:")
print(df1)
print("\nOriginal DataFrame 2:")
print(df2)
print("\nInequality Check:")
print(inequality_check)

Original DataFrame 1:
   A  B
0  1  X
1  2  Y
2  3  Z

Original DataFrame 2:
   A  B
0  1  X
1  2  Y
2  4  W

Inequality Check:
       A      B
0  False  False
1  False  False
2   True   True


**TASK - 1 , QUESTION - 1**

3)a)Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [ ]:
# Create a null vector of size 10
null_vector = np.zeros(10)
# Update the sixth value to 11
null_vector[5] = 11

print("Null vector with the sixth value updated to 11:", null_vector)

Null vector with the sixth value updated to 11: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


b. Write a NumPy program to convert an array to a float type

In [ ]:
# Create an integer array
int_array = np.array([1, 2, 3, 4, 5])
# Convert the array to float type
float_array = int_array.astype(float)
print("Original integer array:", int_array)
print("Array converted to float type:", float_array)

Original integer array: [1 2 3 4 5]
Array converted to float type: [1. 2. 3. 4. 5.]


c. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [ ]:
# Create a 3x3 matrix with values ranging from 2 to 10
matrix_3x3 = np.arange(2, 11).reshape(3, 3)

print("3x3 matrix with values ranging from 2 to 10:")
print(matrix_3x3)

3x3 matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


d. Write a NumPy program to convert a list of numeric value into a one - Numpy array

In [ ]:
# Create a list of numeric values
numeric_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
numeric_array = np.array(numeric_list)

print("List converted to NumPy array:", numeric_array)

List converted to NumPy array: [1 2 3 4 5]


**TASK - 2,QUESTION - 18**

4)Perform Reading data from text files, Excel and the web and exploring various commands
for doing descriptive analytics on the Iris data set

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
data=pd.read_csv("/content/gdrive/MyDrive/IRIS.csv")
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


**CONVERTING THE TEXT FILE INTO EXCEL**

In [ ]:
data.to_excel("/content/gdrive/MyDrive/sample.xlsx")

**SHAPE OF THE DATA**

In [ ]:
data.shape

(150, 5)

**DESCRIBE() THE IRIS DATA**

In [ ]:
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

**NULL VALUE IN AN DATA **

In [ ]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

**INFOMATION ABOUT THE DATA**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


**COUNTS THE VALUES OF SEPAL LENGTH**

In [ ]:
data.value_counts("sepal_length")

sepal_length
5.0    10
6.3     9
5.1     9
5.7     8
6.7     8
6.4     7
5.8     7
5.5     7
5.4     6
6.1     6
5.6     6
6.0     6
4.9     6
4.8     5
6.5     5
6.2     4
5.2     4
4.6     4
7.7     4
6.9     4
7.2     3
5.9     3
4.4     3
6.8     3
4.7     2
6.6     2
7.4     1
7.6     1
7.3     1
4.3     1
7.1     1
7.0     1
5.3     1
4.5     1
7.9     1
dtype: int64

**TASK - 4,QUESTION - 5**

5)Write a Pandas program to get the first 3 rows of a given DataFrame. Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura',
'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
# Sample Python dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura',
                      'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create a DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Get the first 3 rows of the DataFrame
first_3_rows = df.head(3)

print("First 3 rows of the DataFrame:")
print(first_3_rows)

First 3 rows of the DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


**TASK - 3,QUESTION  - 15**

6)Write a Pandas program to get the numeric representation of an array by identifying distinct values
of a given column of a dataframe.

In [ ]:
# Sample DataFrame
data = {'Name': ['John', 'Alice', 'Bob', 'Alice', 'John', 'Bob'],
        'Age': [25, 30, 35, 30, 25, 35],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Los Angeles', 'New York', 'Chicago']}

df = pd.DataFrame(data)

# Choose the column for which you want to get the numeric representation
column_name = 'City'

# Get the numeric representation of the distinct values in the selected column
numeric_representation = pd.factorize(df[column_name])[0]

print(f"Numeric representation of '{column_name}' column:")
print(numeric_representation)

Numeric representation of 'City' column:
[0 1 2 1 0 2]
