# 100 numpy exercises


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a=np.arange(0,20,2,dtype=int)
print(a)
print(a.size)

[ 0  2  4  6  8 10 12 14 16 18]
10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
print(np.add(1.0,4.0))
print(np.info(np.add))

5.0
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    `

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a=np.zeros(10)
print(a)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a=np.array([5,6,7,8])
b=a[ ::-1]
print(b)

[8 7 6 5]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a=np.array([1,2,0,0,4,0])
b=np.where(a == 0)[0]
print(b)

[2 3 5]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a=np.random.random((3,3,3))
print(a)

[[[0.37907738 0.10743062 0.4533172 ]
  [0.26762204 0.73562426 0.16451366]
  [0.88689167 0.73866595 0.43238917]]

 [[0.99614385 0.59852303 0.13817228]
  [0.23418784 0.44106833 0.09446987]
  [0.9310371  0.2321124  0.08252737]]

 [[0.52835837 0.17336766 0.14474297]
  [0.38025222 0.44844257 0.12120693]
  [0.81949651 0.26821394 0.58350467]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a=np.random.random((10,10))
print(a.min())
print(a.max())

0.010140868505739475
0.9968410886771679


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a=np.random.random(30)
print(a.mean())

0.577489907556438


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a=np.ones((5,5))
print(a)
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a=np.ones((3,3))
print(a)
b=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
a=np.ones((3,3))
a=np.zeros((8,8),dtype=int)
a[1::2, ::2]=1
a[ ::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
a=np.unravel_index(99,(6,7,8))
print(a)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
a=np.random.random((5,5))
a=(a-np.mean(a))/(np.std(a))
print(a)

[[-0.57191386 -1.37924555  0.15337421 -1.18575001 -1.16687553]
 [ 1.12690071 -1.21069011 -0.89974779  1.79922155  0.54479456]
 [ 0.70318261  0.99998107  1.30376269 -0.65045233  0.01788439]
 [ 0.53554368 -0.79328761  0.21480002  1.46421353 -1.07956253]
 [-0.66012036  0.76677532 -0.75900632 -0.8913829   1.61760055]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
a=np.dtype([("a",np.ubyte),("b",np.ubyte),("r",np.ubyte),("g",np.ubyte)])
print(a)

[('a', 'u1'), ('b', 'u1'), ('r', 'u1'), ('g', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a=np.ones((5,3)) @ np.ones((3,2))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a=np.arange(11)
a[(3<a)&(a<8)]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=10
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

False

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-30-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-30-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(a)), a))
print(np.where(a>0, np.ceil(a),np.floor(a)))

[-4. -9.  5. -2. -7.  3. -3. -3.  8. -9.]
[-4. -9.  5. -2. -7.  3. -3. -3.  8. -9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a=np.random.randint(0,10,10)
b=np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[0 1 4 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3)/0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-34-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yes=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tmrw=np.datetime64('today')+np.timedelta64(1)
print(yes)
print(today)
print(tmrw)

2023-11-07
2023-11-08
2023-11-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
a=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
a=np.random.uniform(0,10,10)
print(a-a%1)
print(a//a)
print(np.floor(a))
print(np.trunc(a))

[6. 3. 3. 2. 8. 5. 1. 3. 7. 3.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6. 3. 3. 2. 8. 5. 1. 3. 7. 3.]
[6. 3. 3. 2. 8. 5. 1. 3. 7. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
a=np.zeros((5,5))
a+=np.arange(5)
a=np.tile(np.arange(0,5),(5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
  for x in range(10):
    return x
  a=np.fromiter(generate(),dtype=float,count=-1)
  print(a)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
a=np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
a=np.random.random(10)
a.sort()
print(a)

[0.04051    0.25177145 0.29169787 0.3356203  0.4126169  0.59600059
 0.8748874  0.92711658 0.93719795 0.96603486]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
a=np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [3]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [14]:
a = np.zeros(10)
a[0]=1
a.flags.writeable = False
print(a)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [8]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.59780415 0.98338717 0.88015403 0.9937833  0.80624242 0.33105986
 0.37764361 0.70672938 0.68092825 0.69074664]
[0.57789032 1.02013905 1.5003713  0.44016205 1.39146399 0.59020015
 0.54927776 0.18609466 1.151977   1.5140243 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [11]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.70489891 0.11811679 0.29041356 0.         0.48057082 0.21068631
 0.54869195 0.57407401 0.86872279 0.45532768]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [12]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [15]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [16]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [18]:
np.set_printoptions(threshold=float("inf"))
a= np.zeros((20,20))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [19]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [20]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-20-1c50e4e32ac3>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [21]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.46667161 0.41991955 0.70042123 0.80899006 0.58545636
  0.25633349 0.13097344 0.23503504 0.43996016]
 [0.46667161 0.         0.14769007 0.83369976 0.93871426 0.913566
  0.70291086 0.39878883 0.63933862 0.14427343]
 [0.41991955 0.14769007 0.         0.68684919 0.79129204 0.78767049
  0.67377215 0.39439867 0.54693043 0.02010092]
 [0.70042123 0.83369976 0.68684919 0.         0.11124282 0.36380533
  0.85621057 0.80573721 0.53979386 0.69410834]
 [0.80899006 0.93871426 0.79129204 0.11124282 0.         0.41491883
  0.95532488 0.91612034 0.6388988  0.79753818]
 [0.58545636 0.913566   0.78767049 0.36380533 0.41491883 0.
  0.63180452 0.71531291 0.35433734 0.80269396]
 [0.25633349 0.70291086 0.67377215 0.85621057 0.95532488 0.63180452
  0.         0.30754501 0.31661163 0.69366477]
 [0.13097344 0.39878883 0.39439867 0.80573721 0.91612034 0.71531291
  0.30754501 0.         0.36600816 0.41301451]
 [0.23503504 0.63933862 0.54693043 0.53979386 0.6388988  0.35433734
  0.31661163 0.3660081

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [22]:
x = (np.random.rand(10)*100).astype(np.float32)
Y = x.view(np.int32)
Y[:] = x
print(Y)

[35 38 14 78 29 49 53 51 29 12]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [23]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
l= np.genfromtxt(s, delimiter=",", dtype=np.int)
print(l)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-23-2c336ed93727>:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  l= np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [24]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [25]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [26]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [27]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.1223693   0.13688645 -0.36968951  0.13404163  0.12842796 -0.17409403
   0.41309077 -0.30646195 -0.09519482  0.2553628 ]
 [ 0.28412597 -0.24461676 -0.12806955 -0.13911974  0.22527845 -0.33097867
   0.44044541 -0.3383718   0.06445329  0.1668534 ]
 [-0.2267037   0.59123757 -0.21992858 -0.35533232  0.19087091 -0.37315732
   0.06716885 -0.16840789  0.46731919  0.02693328]
 [ 0.2997442  -0.5967262   0.02346206 -0.03299523  0.27067811 -0.22888451
  -0.00982567 -0.33472733  0.33408107  0.27519351]
 [-0.01302957  0.17448941 -0.22905607 -0.33735736  0.21854534  0.17353313
  -0.08510305  0.2411003  -0.38379114  0.24066901]]


#### 59. How to sort an array by the nth column? (★★☆)

In [28]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[1 5 7]
 [1 9 1]
 [0 5 7]]
[[1 5 7]
 [0 5 7]
 [1 9 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [29]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [30]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4989164541337704


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [31]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [32]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")
h= NamedArray(np.arange(10), "range_10")
print (h.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [33]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[3. 2. 4. 4. 5. 3. 1. 1. 3. 4.]
[5. 3. 7. 7. 9. 5. 1. 1. 5. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [34]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [35]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [36]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[51 57 59 40]
 [55 43 60 57]
 [53 64 54 73]]
[[51 57 59 40]
 [55 43 60 57]
 [53 64 54 73]]


 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [37]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
print(pd.Series(D).groupby(S).mean())

[0.49154908 0.48546484 0.44836619 0.32736607 0.45483948 0.57670354
 0.27064867 0.56369817 0.4840375  0.51483949]
0    0.491549
1    0.485465
2    0.448366
3    0.327366
4    0.454839
5    0.576704
6    0.270649
7    0.563698
8    0.484038
9    0.514839
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [38]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([0.98666214, 1.87008003, 0.89324666, 0.60964803, 1.73408612])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [39]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [40]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [41]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [42]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4,  5) ( 4, 93) ( 5, 93) (13, 25) (13, 69) (17, 39) (17, 80) (20, 54)
 (20, 62) (25, 69) (34, 60) (34, 96) (39, 80) (40, 67) (40, 78) (44, 79)
 (44, 80) (54, 62) (60, 79) (60, 92) (60, 96) (61, 72) (61, 74) (67, 71)
 (67, 78) (67, 88) (71, 88) (72, 74) (79, 80) (79, 92)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [43]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [44]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [45]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [46]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.29241408,  0.91582615,  0.3267665 , -0.1502159 ,  0.33991753,
       -0.61762575, -0.53870683, -0.32852153, -0.63588474,  0.38278865,
       -0.92205452,  0.79255933, -0.74218813, -0.45243642,  0.90951849,
        0.18406767,  0.83765072, -0.90069676,  0.33400678,  0.24587906,
       -0.36920234,  0.30713242, -0.90344982, -0.68881153, -0.92608803,
        0.62734454,  0.45911889, -0.29166475, -0.24758843,  0.43598746,
       -0.51876364,  0.30155201,  0.9392467 ,  0.12618071, -0.12568093,
        0.21047112,  0.90884979,  0.71239038, -0.6866186 , -0.90488914,
        0.47859709,  0.57681143, -0.90705537, -0.6379264 , -0.32416793,
       -0.91326123, -0.20760778,  0.44762095, -0.38025443,  0.37057259,
       -0.60084884, -0.12038303, -0.4485427 , -0.52613742,  0.21518864,
        0.25284515, -0.922004  ,  0.96416028, -0.97799802, -0.38550392,
       -0.19805642, -0.5727567 , -0.58964907,  0.92547926, -0.04969023,
       -0.24409115, -0.01197369, -0.03681995, -0.69568483, -0.59

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [47]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.75292575 4.63790694 3.59137254 0.91476488 5.38776769 3.59206561
 0.139372   3.92356864 5.17789572 2.13131336]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [48]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.99748231  1.5143184   8.57671194  8.87087987  5.67625953  3.03669921
  10.98350826  8.99966603  0.53945066 11.2817164 ]
 [ 2.37358332  3.63109008  5.06223861  4.52029608  7.58796958  2.24954986
   5.34369803  4.23054254  5.89173526  7.3512064 ]
 [12.45852595 15.16030125  4.79291174  3.61070819  3.8275542   9.96135841
   5.53128219 10.46544078  2.35995333  1.73848146]
 [11.85206978 15.33953308  4.08965635  2.30165865  6.01806539 10.88193408
   8.38440981 13.53293414  0.7091515   0.74375461]
 [11.64044063 11.2037522   4.37649867  5.79082898  7.06047666  3.24054136
   4.40240571  1.96028844 14.00912688  2.55281841]
 [13.99130287 17.23952742  6.24931491  4.53922421  6.6405647  12.4373348
   6.63308412 12.70293751  0.59359834  2.95208261]
 [ 1.9561257   1.08178496  9.32332484  8.23378657 11.707832    7.04269017
   6.04084705  2.48836555  6.51709425 11.37529264]
 [13.87409021 15.24408016  6.37076162  6.19428362  0.37021984  8.76494866
   0.52006072  5.28649848  7.63527581  3.80244359]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [72]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
print(Z)
print(R)

[[2 6 7 3 5 2 1 0 0 4]
 [2 8 7 4 1 2 1 1 9 0]
 [5 4 6 1 5 7 1 9 9 1]
 [2 9 3 6 1 9 7 0 5 2]
 [4 8 5 1 6 4 7 7 5 0]
 [6 7 3 6 1 9 4 7 5 7]
 [6 5 9 6 8 6 3 5 1 8]
 [1 5 0 6 1 6 5 8 7 9]
 [9 3 7 3 9 4 6 8 6 0]
 [4 7 9 9 1 8 6 3 7 4]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [51]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [52]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)
rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array?

In [53]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [55]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[0 4 1]
   [3 1 2]
   [2 3 1]]

  [[4 1 4]
   [1 2 4]
   [3 1 0]]

  [[1 4 3]
   [2 4 2]
   [1 0 0]]

  [[4 3 0]
   [4 2 4]
   [0 0 3]]

  [[3 0 3]
   [2 4 4]
   [0 3 0]]

  [[0 3 0]
   [4 4 2]
   [3 0 4]]

  [[3 0 2]
   [4 2 3]
   [0 4 2]]

  [[0 2 2]
   [2 3 3]
   [4 2 3]]]


 [[[3 1 2]
   [2 3 1]
   [0 0 0]]

  [[1 2 4]
   [3 1 0]
   [0 0 3]]

  [[2 4 2]
   [1 0 0]
   [0 3 1]]

  [[4 2 4]
   [0 0 3]
   [3 1 1]]

  [[2 4 4]
   [0 3 0]
   [1 1 1]]

  [[4 4 2]
   [3 0 4]
   [1 1 1]]

  [[4 2 3]
   [0 4 2]
   [1 1 0]]

  [[2 3 3]
   [4 2 3]
   [1 0 0]]]


 [[[2 3 1]
   [0 0 0]
   [0 1 4]]

  [[3 1 0]
   [0 0 3]
   [1 4 2]]

  [[1 0 0]
   [0 3 1]
   [4 2 4]]

  [[0 0 3]
   [3 1 1]
   [2 4 2]]

  [[0 3 0]
   [1 1 1]
   [4 2 2]]

  [[3 0 4]
   [1 1 1]
   [2 2 1]]

  [[0 4 2]
   [1 1 0]
   [2 1 2]]

  [[4 2 3]
   [1 0 0]
   [1 2 3]]]


 [[[0 0 0]
   [0 1 4]
   [2 4 2]]

  [[0 0 3]
   [1 4 2]
   [4 2 1]]

  [[0 3 1]
   [4 2 4]
   [2 1 2]]

  [[3 1 1]
   [2 4 2]
   [1 2 2]]

  [[1 1 1]
   

 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [56]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 11 11  8 11]
 [11  6  8 14  1]
 [11  8  9 42  9]
 [ 8 14 42  5  1]
 [11  1  9  1  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [57]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [58]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)
Z = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [59]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
  0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 1 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 1 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [60]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9999 9996 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [61]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [62]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [63]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.83 s ± 524 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
224 ms ± 1.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
202 ms ± 2.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [64]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [65]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 0 1]
 [1 0 0]
 [0 4 0]
 [2 0 0]
 [3 0 1]
 [3 3 3]
 [4 3 0]
 [2 3 4]
 [2 4 2]
 [1 2 2]]
[[1 0 1]
 [1 0 0]
 [0 4 0]
 [2 0 0]
 [3 0 1]
 [4 3 0]
 [2 3 4]
 [2 4 2]
 [1 2 2]]
[[1 0 1]
 [1 0 0]
 [0 4 0]
 [2 0 0]
 [3 0 1]
 [4 3 0]
 [2 3 4]
 [2 4 2]
 [1 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [66]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [67]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [68]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[4.37732174e-02, 8.02047938e-03, 6.93275059e-03, 5.21458726e-02,
        4.25469627e-02, 1.10269410e-02, 2.62349082e-02, 3.36438636e-02,
        3.61623629e-02, 4.23662200e-02],
       [1.04788710e-01, 1.92002265e-02, 1.65963125e-02, 1.24832011e-01,
        1.01853179e-01, 2.63973953e-02, 6.28037499e-02, 8.05400491e-02,
        8.65690849e-02, 1.01420499e-01],
       [2.15950167e-01, 3.95681186e-02, 3.42019329e-02, 2.57255705e-01,
        2.09900579e-01, 5.44001534e-02, 1.29426922e-01, 1.65978157e-01,
        1.78402886e-01, 2.09008906e-01],
       [4.03368709e-01, 7.39084445e-02, 6.38850607e-02, 4.80522441e-01,
        3.92068813e-01, 1.01612886e-01, 2.41753786e-01, 3.10027058e-01,
        3.33234943e-01, 3.90403275e-01],
       [4.53522406e-01, 8.30980064e-02, 7.18283442e-02, 5.40269210e-01,
        4.40817514e-01, 1.14247138e-01, 2.71812752e-01, 3.48574924e-01,
        3.74668411e-01, 4.38944888e-01],
       [4.75463973e-01, 8.71183160e-02, 7.53034237e-02, 5.66407616e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [69]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [70]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [71]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1875898   0.22262517]
